### PR TITLE
🚲 shed

### PR DESCRIPTION
**Pull request by Coder-256**
Here you go. This is clean and future-proof. I can't promise that it will deploy, but it definitely should and is not a pain to maintain.

Also, [why don't you use Typescript?](https://firebase.googleblog.com/2018/01/why-you-should-use-typescript-for.html)

### CODE REVIEW

**Comment by christopherm99** [comment]
Ok, will merge this to see if it will deploy. Thank you for cleaning that up.
I don't plan to use TypeScript for the entire project, for various reasons, but perhaps I will switch for the cloud functions.

**Comment by Coder-256** [comment]
I would *very highly* recommend using TypeScript for the entire project. What are your reasons?

**Comment by christopherm99** [comment]
1. I have had serious issues with TypeScript in the past (finding type declarations for certain more obscure packages is difficult, and I'd prefer to just not use types instead of writing my own).
2. I've already written most of the project in JavaScript.
3. TypeScript's benefits don't make it seem worth converting.
4. I've been asked to use JavaScript specifically.

**Comment by Coder-256** [comment]
1. Fair enough. I feel your pain. More and more packages are getting TS support, but if you have an important package that doesn't support TS then I understand.
2. Not fair enough, I don't think it's too difficult to convert 99% of the changes in TS are optional, but I could be wrong.
3. Not fair enough at all! It has stopped me from making so many mistakes (using a string instead of a number, etc.) and it has actual classes with inheritance and stuff. More importantly, as I said, it tells you when you use the wrong type, or the wrong number of arguments, or misspell a function name, which is especially useful when using libraries like Firebase. The compiler can't really do that without TS, unless you use [Flow](https://flow.org/) or something (which I would recommend if you really can't use TS).
4. Really? That seems a bit odd to me. TypeScript is very readable, so if that's the concern I wouldn't worry at all.

In the end it's your project, but IMO it would be worth converting to TypeScript.

**Comment by Coder-256** [comment]
Also, unrelated, I wouldn't hardcode the allowed admins in your security rules, instead it might be better to store that in Firestore just so that you can add new admins from the website without deploying new security rules.

**Comment by christopherm99** [comment]
I'll look in to using Flow, but I still don't think I'll switch completely to ts.

About the admins, I plan to switch that also, in the next commit.

**Comment by Coder-256** [comment]
Ok, I guess that's a good middle ground. I still have to disagree, I think TS is better in your case, but Flow is also good-ish and I guess it still has most of the benefits of TS.

**Pull request merged**
